version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps:"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci:"

  - package-ecosystem: npm
    directory: /packages/solana-credential-helper-ts
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps:"
