[package]
name = "solana-keyring-biometric"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Biometric authentication (TouchID) for Solana keyring"

[dependencies]
thiserror.workspace = true

[dev-dependencies]

[lints]
workspace = true
